### ISSUE TITLE
Recipe viewer item placement bug

### ISSUE THREAD

**Issue by Silik0n** [DutchJelly/CraftEnhance#37]
An item gets stuck at the bottom row of the recipe viewer.

In order to preform this bug, you must
1: create a recipe on the last slot of a page
2: go into recipe viewer and edit the last item on the page
3: remove the product of the recipe and save
4: on opening the recipe viewer again, there should be a bugged recipe at the bottom right of the menu

This doesn't crash or break anything, its more visual so I don't think a files check should be needed

![what](https://user-images.githubusercontent.com/86142675/122632862-6bb1e780-d0a3-11eb-8eb9-6ba2a797fec0.png)

**Comment by DutchJelly** [comment]
Thanks for reporting this bug. I think it could be caused by an error in the `guitemplates.yml`. The indexing is faulty.
```yml
RecipesViewer:
  name: "recipes viewer"
  fill-space: "0-45" # error: this should be "0-44"
  button-mapping:
    48: PrvPage
```
